const CUSTOMER_ID_UUID_VERSION = 4;
const SERIAL_NUMBER_LENGTH = 11;
const MPXN_LENGTH = 8;
const REQUIRED_READ_TYPES = ["ANYTIME", "NIGHT"];

module.exports = {
  CUSTOMER_ID_UUID_VERSION,
  SERIAL_NUMBER_LENGTH,
  MPXN_LENGTH,
  REQUIRED_READ_TYPES
};
