version: 2
jobs:
  build:
    docker:
      # specify the docker version you desire here
      - image: circleci/node:12.8.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run:
          name: run tests with coverage reports
          command: npm run test-coverage

      # Upload coverage report to codecov
      - run:
          name: upload test reports to codecov
          command: npm run report-coverage
